### ISSUE TITLE
How to handle AppTrackingTransparency

### ISSUE THREAD

**Issue by ciaoben** [tapdaq/cordova-plugin#10]
Hi, 
Is there a documented/official way to handle the upcoming AppTrackingTransparency changes from Apple?

https://developer.apple.com/documentation/apptrackingtransparency

**Comment by rdominic** [comment]
Whilst we recommend that you do use ATT to request permission to use the IDFA, we do not provide an interface for this, there are however plugins available for this purpose.

**Comment by ciaoben** [comment]
@rdominic I understand, thanks for the response. I can't find any valid plugin, do you have any reference/suggestion?

**Comment by rdominic** [comment]
This looks like it should work for you
https://github.com/chemerisuk/cordova-plugin-idfa

Note, we haven't tested this yet, but we will look at doing so and including this or similar in our test app
