### ISSUE TITLE
( ERROR ) cordova plugin add @tapdaq/cordova-pangle-adapter

### ISSUE THREAD

**Issue by EMI-INDO** [tapdaq/cordova-plugin#11]
![123](https://user-images.githubusercontent.com/78555833/119236321-f95fed00-bb60-11eb-8157-acd8f5406c5e.png)

**Comment by rdominic** [comment]
Apologies @EMI-INDO it appears the package was private. Please try again now.

_Note that Pangle is currently only supported on iOS, Android builds simply ignore it._

**Comment by EMI-INDO** [comment]
### Thank you friend
