### ISSUE TITLE
Init Method not working

### ISSUE THREAD

**Issue by shoaib07860** [tapdaq/cordova-plugin#12]
Recently I integrated the required plugin and setup the code as mentioned in document.
On device ready, Tapdaq is able  to access plugin but  Tapdaq.init(config, opts); not working
Not even any error.
And When called Tapdaq.launchDebugger();
It showing SDK status False

Is there anything I am missing?

**Comment by rdominic** [comment]
Please provide a screenshot of the debugger > Info page

You may also want to set debug mode in your config which will enable more logs
```javascript
var config = {
            logLevel: Tapdaq.LogLevel.Debug
        };
```

**Comment by rdominic** [comment]
Apologies we couldn't help here. Unfortunately Tapdaq is being deprecated and its services turned off.
All public SDK repo's will be archived shortly and changed to private later this year.

For an alternative mediation platform we recommend IronSource.

Closing this ticket.
