### ISSUE TITLE
Not able to add cordova-plugin-tapdaq-admob to the project

### ISSUE THREAD

**Issue by ashishsukhija** [tapdaq/cordova-plugin#2]
\blabberbuzzcordova1>cordova plugin add cordova-plugin-tapdaq-admob
Error: Not found : cordova-plugin-tapdaq-admob

I am on cordova 7.1.0

**Comment by rdominic** [comment]
A new version is now available, 4.0.0 and is again on npm.

Apologies for the inconvenience
