### ISSUE TITLE
Calling init cause the app to crash

### ISSUE THREAD

**Issue by EYALIN** [tapdaq/cordova-plugin#26]
hi,

tried your demo and all works fine. when I'm moving to my apps, the Init method causes the app to crash.
since I don't have your Tapdaq.java code (where the exception is thrown), so I can't debug it.
can you please help me with this?

this is what I get from logcat:
`09-27 17:07:04.285  4724  4796 E AndroidRuntime: FATAL EXCEPTION: pool-3-thread-2
09-27 17:07:04.285  4724  4796 E AndroidRuntime: Process: com.yalin.xxxxxxx, PID: 4724
09-27 17:07:04.285  4724  4796 E AndroidRuntime: java.lang.IllegalStateException: Method addObserver must be called on the main thread
09-27 17:07:04.285  4724  4796 E AndroidRuntime:        at androidx.lifecycle.LifecycleRegistry.enforceMainThreadIfNeeded(LifecycleRegistry.java:317)
09-27 17:07:04.285  4724  4796 E AndroidRuntime:        at androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.java:172)
09-27 17:07:04.285  4724  4796 E AndroidRuntime:        at com.tapdaq.sdk.TDLifecycleObserver.RegisterCallbacks(TDLifecycleObserver.java:19)
09-27 17:07:04.285  4724  4796 E AndroidRuntime:        at com.tapdaq.sdk.Tapdaq.initialize(Tapdaq.java:65)
09-27 17:07:04.285  4724  4796 E AndroidRuntime:        at com.tapdaq.cordovasdk.CDVTapdaq$1.run(CDVTapdaq.java:231)
09-27 17:07:04.285  4724  4796 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
09-27 17:07:04.285  4724  4796 E AndroidRuntime:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
09-27 17:07:04.285  4724  4796 E AndroidRuntime:        at java.lang.Thread.run(Thread.java:762)`

**Comment by rdominic** [comment]
Thanks for getting in touch, I believe you have also been in touch with our integrations team which is great. As they have said, we're working on providing a fix for Cordova 10 ASAP.

**Comment by rdominic** [comment]
We've now pushed an update v4.4.2 to support https & Cordova Android 10. Please update and let us know if you have any further issues.

Thanks for your patience
