### ISSUE TITLE
Cordova Android update

### ISSUE THREAD

**Issue by EMI-INDO** [tapdaq/cordova-plugin#27]
`Hi Cordova Android update: 9.0.0 to 10.0.0`

cordova platform add android@9.0.0   build success
cordova platform add android@10.0.0   build error
cordova platform add android@10.1.1   build error

![err](https://user-images.githubusercontent.com/78555833/135150221-3325f6ba-85e3-4e78-b81a-bdb2d8bbeb04.png)

**Comment by rdominic** [comment]
Thanks for getting in touch, we're working on an update for Cordova 10 which we'll release ASAP.

**Comment by rdominic** [comment]
We've now pushed an update v4.4.2 to support https & Cordova Android 10. Please update and let us know if you have any further issues.

Thanks for your patience
