### ISSUE TITLE
app crach when i call init

### ISSUE THREAD

**Issue by diaxotora** [tapdaq/cordova-plugin#28]
Hello,
I just installed the Tapdaq SDK on my app with the facebook adapter in addition to the admob adapter but this one made the app crach on startup so I removed it, so when I copied the code from initializing Tapdaq in my code the app also crach on startup, can you help me initialize Tapdaq well and if you can also tell me how to install the admob adapter.
Thank you

**Comment by diaxotora** [comment]
Hello here is my new code : 
function onDeviceReady() {
    const Tapdaq = cordova.require("cordova-plugin-tapdaq.Tapdaq");

    const config = {
        android: {
            appId: "xxxxxxxx",
            clientKey: "xxxxxx"
        }
    };
        
    const opts = {
        didInitialise: function() {
            // Tapdaq has initialised
            console.log("Tapdaq initialised");
        },
        didFailToInitialise: function(error) {
            // Tapdaq failed to initialised
            console.log(error);
        }
    };

    Tapdaq.init(config, opts);
}
function onLoad() {
    document.addEventListener("deviceready", onDeviceReady, false);
}

App crach when i run it on my device

**Comment by rdominic** [comment]
Is this using Cordova 10? If so this is a known issue we're working to provide an update as soon as possible.
Please provide error logs to confirm it's the same issue.

Thanks,
Dominic

**Comment by diaxotora** [comment]
Hi,
i downgrade cordova to 9.0 and i have cordova-android 8.1 and gradel 4.10.3 but when i install tapdaq and the adapters and i build the project i have this error : 

[com.facebook.android:audience-network-sdk:6.5.0] C:\Users\k_ben\.gradle\caches\transforms-1\files-1.1\audience-network-sdk-6.5.0.aar\8a842ca300fa35318b20ad49f111ea72\AndroidManifest.xml:12:9-55 Error:
        Missing 'package' key attribute on element package at [com.facebook.android:audience-network-sdk:6.5.0] AndroidManifest.xml:12:9-55
[com.facebook.android:audience-network-sdk:6.5.0] C:\Users\k_ben\.gradle\caches\transforms-1\files-1.1\audience-network-sdk-6.5.0.aar\8a842ca300fa35318b20ad49f111ea72\AndroidManifest.xml Error:
        Validation failed, exiting

FAILURE: Build failed with an exception.
How to solve this problem please
Thanks

**Comment by rdominic** [comment]
That error is due to a new(ish) element in the Facebook Audience Network AndroidManifest.xml, it requires a newer version of gradle.

The line in particular:
```xml
    <queries>
        <package android:name="com.facebook.katana" />
    </queries>
```

See https://stackoverflow.com/questions/62969917/how-to-fix-unexpected-element-queries-found-in-manifest-error

We have now also released Cordova Plugin 4.4.2 update which supports Cordova Android 10, updating to that may solve all your issues.

**Comment by diaxotora** [comment]
hi, i use this plugin 4.4.2 with cordova-android@10.0.0 and gradle 7.2 and when i install the plugin without adapters app crach in startup without integrating init code 
Thanks for your help

**Comment by rdominic** [comment]
Are there any logs for this crash?

**Comment by diaxotora** [comment]
finally I noticed that the app spits that when I install admob-adapter while integrating the multidex, apart from that I managed to initialize the sdk with fan-adapter without multidex,
please i want admob and fan at the same time how to do?
ps: There is no log or errors

**Comment by rdominic** [comment]
Apologies we couldn't help here. Unfortunately Tapdaq is being deprecated and its services turned off.
All public SDK repo's will be archived shortly and changed to private later this year.

For an alternative mediation platform we recommend IronSource.

Closing this ticket.
