### ISSUE TITLE
how to integrate native ads ?

### ISSUE THREAD

**Issue by diaxotora** [tapdaq/cordova-plugin#29]
Hi,
I added facebook audience network as a source of request on the tapdaq mediation and I integrated banner and interstial ads successfuly but i don't find any documentation about native ads please help
Thank you

**Comment by rdominic** [comment]
@diaxotora unfortunately we do not support Native Ads for Cordova.

Facebook Audience Network have also recently moved to a bidding only approach for which we only support Video & Rewarded Video.

https://en-gb.facebook.com/audiencenetwork/resources/blog/audience-network-to-become-bidding-only-beginning-with-ios-in-2021

Please contact support@tapdaq.com for further integration help.

**Comment by diaxotora** [comment]
ok thank you @rdominic
