### ISSUE TITLE
Bump Adcolony version in plugin

### ISSUE THREAD

**Issue by ciaoben** [tapdaq/cordova-plugin#30]
Hi, thanks for the good work.

I notice that on the last versione the `Adcolony` SDK version specified as a dependency is `4.6.1`.
The last available version is `4.7.2`. It does not bring a ton on news but it has one very important: the support for the Mac's M1 processor in the emulator.

I think the number of M1 machines is going to increase a lot with these new devices that Apple introduced, it would be great bump the version to add support to them.

I am not an iOS developer so I don't know how to create a safe pull request, sorry!

**Comment by rdominic** [comment]
We are planning to update all network dependencies in our next release by the end of the year, the updates appear to have some minor interface changes so our adapter will likely need some updates to be compatible with AdColony's latest release.

**Comment by rdominic** [comment]
We pushed an update in December with the latest AdColony if you still need this.
