### ISSUE TITLE
Application does not open

### ISSUE THREAD

**Issue by 4quarenta** [tapdaq/cordova-plugin#32]
when installing 

``cordova plugin add @tapdaq/cordova-admob-adapter``

the app crashes and no longer opens

![image](https://user-images.githubusercontent.com/70922568/152405345-0e33e1b5-21a2-4d7f-afed-889cbe019dfb.png)

**Comment by rdominic** [comment]
Hi @4quarenta are you targeting Android API 31? If so you need to add this additional dependency to the gradle file.

```groovy
implementation('androidx.work:work-runtime:2.7.0')
```

See https://developers.google.com/admob/android/rel-notes#20.4.0

Otherwise change your target API to 30

**Comment by rdominic** [comment]
Apologies we couldn't help here. Unfortunately Tapdaq is being deprecated and its services turned off.
All public SDK repo's will be archived shortly and changed to private later this year.

For an alternative mediation platform we recommend IronSource.

Closing this ticket.
