### ISSUE TITLE
Ionic Support!

### ISSUE THREAD

**Issue by elkhalifte** [tapdaq/cordova-plugin#6]
Is this plugin works on ionic 4+?

**Comment by elkhalifte** [comment]
Please add a native plugin for ionic

**Comment by darkguy2008** [comment]
So no Ionic so far? I was recommended Tapdaq from another issue ( https://github.com/admob-plus/admob-plus/issues/209#issuecomment-750037399 ) but if it's not in Ionic I'm afraid I can't use it :/

**Comment by dknussmann** [comment]
Yes please! Full ionic integration would be great

Edit: 
Does anyone have a dossier on how to add ionic support?

**Comment by rdominic** [comment]
Sorry, we do not have any plans to support Ionic at the moment, the source code for this plugin is available in this repository, so you are free to fork and modify.

**Comment by darkguy2008** [comment]
> Sorry, we do not have any plans to support Ionic at the moment, the source code for this plugin is available in this repository, so you are free to fork and modify.

Thanks, but I don't think that's the kind of answer for the users who would want to use your platform with a framework that's also being used and actively developed. What benefit would it give me to use it if the support is like this?

I ended up moving my app to Capacitor instead, but other users may not have it so easy.

**Comment by rdominic** [comment]
Apologies we couldn't help here. Unfortunately Tapdaq is being deprecated and its services turned off.
All public SDK repo's will be archived shortly and changed to private later this year.

For an alternative mediation platform we recommend IronSource.

Closing this ticket.
