### ISSUE TITLE
Can't debug app with Chrome DevTools after plugin is loaded

### ISSUE THREAD

**Issue by bartguz** [tapdaq/cordova-plugin#7]
Hello
Doing `const tapdaq = cordova.require('cordova-plugin-tapdaq.Tapdaq'); tapdaq.init(config, opts);`
makes app disappear from Chrome DevTools.

After launching app, it is visible for a split of second in Chrome, then id disappears.
App built with said code removed but still with plugins included is possible to debug.

Ionic v4 
@tapdaq/cordova-sdk 4.2.0

**Comment by rdominic** [comment]
Apologies we couldn't help here. Unfortunately Tapdaq is being deprecated and its services turned off.
All public SDK repo's will be archived shortly and changed to private later this year.

For an alternative mediation platform we recommend IronSource.

Closing this ticket.
