### ISSUE TITLE
Repository not found

### ISSUE THREAD

**Issue by sprengerst** [tapdaq/cordova-plugin#8]
Hi, 

if I add the cordova-plugin-tapdaq then I get the error:
fatal: repository 'https://github.com/tapdaq/tapdaq-ios-sdk.git/' not found

I looked into my podfile and saw that there is a wrong version linked:
	pod 'Tapdaq', '~> 5.10.0'
	
I think 5.10.0 is not available anymore.

Could you please update the npm registry? 
https://www.npmjs.com/package/cordova-plugin-tapdaq

**Comment by sprengerst** [comment]
If I upgrade to version 7.8 it bricks the build. So I think an update is needed here.

Do you know what could be the problem here?

**Comment by sprengerst** [comment]
I manage to fix the issue. 
I removed all plugins and installed them again.

So remove all references to tapdaq plugins from package.json. 
Delete folder npm-modules, plugins and platforms (if you use ionic)

Afterwards call the commands that you are told to call from the documentation (in my case):
cordova plugin add @tapdaq/cordova-sdk
cordova plugin add @tapdaq/cordova-applovin-adapter
cordova plugin add @tapdaq/cordova-inmobi-adapter
cordova plugin add @tapdaq/cordova-unityads-adapter

**Comment by monokaijs** [comment]
Same issue here.

**Comment by rdominic** [comment]
Apologies we couldn't help here. Unfortunately Tapdaq is being deprecated and its services turned off.
All public SDK repo's will be archived shortly and changed to private later this year.

For an alternative mediation platform we recommend IronSource.

Closing this ticket.
